[32m2024-06-15 20:41:29 +0545[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 63038aa5-5234-45e7-bab3-44fba63b09d5 - 372121 - LOGS_CAPTURED - Started capturing logs in process (pid: 372121).
[32m2024-06-15 20:41:29 +0545[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 63038aa5-5234-45e7-bab3-44fba63b09d5 - 372121 - taxi_trips_file - STEP_START - Started execution of step "taxi_trips_file".
[32m2024-06-15 20:41:36 +0545[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 63038aa5-5234-45e7-bab3-44fba63b09d5 - 372121 - taxi_trips_file - STEP_FAILURE - Execution of step "taxi_trips_file" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "taxi_trips_file"::

NameError: name 'constants' is not defined

Stack Trace:
  File "/home/mikeyy/projects/personal_projects/Looking-Into-Dagster/venv/lib/python3.10/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/home/mikeyy/projects/personal_projects/Looking-Into-Dagster/venv/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 468, in iterate_with_context
    next_output = next(iterator)
  File "/home/mikeyy/projects/personal_projects/Looking-Into-Dagster/venv/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/home/mikeyy/projects/personal_projects/Looking-Into-Dagster/venv/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/home/mikeyy/projects/personal_projects/Looking-Into-Dagster/dagster_university/dagster_university/assets/trips.py", line 17, in taxi_trips_file
    constants.TAXI_TRIPS_TEMPLATE_FILE_PATH.format(month_to_fetch), "wb"
[0m
